// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.png" {
  const path: `${string}.png`;
  export = path;
}

declare module "*.jpg" {
  const path: `${string}.jpg`;
  export = path;
}

declare module "*.jpeg" {
  const path: `${string}.jpeg`;
  export = path;
}

declare module "*.ico" {
  const path: `${string}.ico`;
  export = path;
}

declare module "*.wav" {
  const path: `${string}.wav`;
  export = path;
}

declare module "*.mp3" {
  const path: `${string}.mp3`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
